# Generated by Django 3.1.1 on 2020-09-26 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontentvideos',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_content_videos', to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='coursecontentvideos',
            name='course_heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_heading_videos', to='courses.coursecontentheadings'),
        ),
    ]
